version: "3"

services:
  portfolio-orchestrator:
    container_name: "portfolio-orchestrator"
    image: "portfolio-orchestrator"
    build: ..
    ports:
      - "0.0.0.0:8080:8080"
    env_file: ../.env
    environment:
      PORT: 8080
    networks:
      - xosedev
networks:
  xosedev: